### ISSUE TITLE
🤖 - Performance checklist 

### ISSUE THREAD

**Issue by riccardoperra** [riccardoperra/codeimage#264]
### Description

CodeImage was born in February, about a month has passed since the end of SolidHack. There are some open points that will be resolved over the time:

- [x] #202 
- [x] Analyze how to improve bundle size
- [ ] Analyze a better way to manage state, considering https://github.com/riccardoperra/codeimage/issues/238
- [X] Improve codemirror performance with the latest version partial update features https://github.com/riccardoperra/codeimage/pull/298
- [ ] Analyze better DOM structure to improve performance and reaction to changes
- [x] https://github.com/riccardoperra/codeimage/issues/170
- [X] Chunk splitting for @codeimage/theme https://github.com/riccardoperra/codeimage/pull/280
- [X] Theme lazy loading + suspense
- [X] Split chunks for main app
- [X] InlineComboBox should be loaded in lazy loading
- [X] Split chunks for CodeMirror editor in order to defer his loading after main app

**Comment by riccardoperra** [comment]
![image](https://user-images.githubusercontent.com/37072694/172072030-ff9ddd9e-2dfb-4324-ae9d-661a0e16e17a.png)

![image](https://user-images.githubusercontent.com/37072694/172072037-7a1784df-85b1-4fc5-b7e6-0e43e87961dc.png)

### 4x slowdown
![image](https://user-images.githubusercontent.com/37072694/172072129-37fbb9b2-874c-4888-9ab3-9720b3e5df9f.png)

### No throttling

![image](https://user-images.githubusercontent.com/37072694/172072166-759d5e78-5b97-4608-8824-8105be8071d9.png)
