### ISSUE TITLE
[Task Checklist] 🚀 Projects - 1.0 Release

### ISSUE THREAD

**Issue by riccardoperra** [riccardoperra/codeimage#325]
<div type='discussions-op-text'>

### Which @codeimage/* package(s) are relevant/releated to the feature request?

codeimage, config, locale, highlight, ui

### Description

CodeImage projects will be the new way to store the snippets remotely. It will be the feature that will bring CodeImage to 1.0 version. Currently all the data is always saved locally, and you can have one opened snippet at time. Thanks to Projects, any authenticated user will be able to save their snippets remotely and retrieve them in any time.

## Dashboard

The dashboard will be the newest page of Projects. It will be accessible from the /dashboard url path and only for authenticated  users.

> **Note** The dashboard page is still under construction. Still not clear if it will be a new page or a full screen overlay

Each project in the list will show these basic informations:
- Name
- used
- Create date
- Last update date

![image](https://user-images.githubusercontent.com/37072694/183310032-6a818f16-692f-4a0a-8a60-276f842cc4ec.png)

Once a project has been created, from the dashboard it will be possible to remove, change the name or clone an existing project.

Also, since each project is stored in the db, it will be publicly accessible with a link for anyone. Of course, only the creator user will be able to edit the snippet. For other users, there will be a lighter view without the editor, but with the possibility of inserting the project in their workspace in order to manage it.

> **Note** Currently there are no limits of project creation

## UI improvements

This release wll make some improvements to the editor UI. First, `inter-ui` font will be updated using the right font-variants. All the setting buttons like languages or theme will be moved into a new Settings dialog available through a menu.

Also, if not authenticated a `Sign in` button will be visible for everyone.

## Backend

Project obviously needs a backend in order to sync the data remotely. It will be created a new package `api` which will contain the public source code of the fastify rest api backend. It will also be integrated with [Prisma](https://github.com/prisma/prisma) orm

Here the api routes that will be exposed from the backend:
- [GET] /api/v1/project - Get the list of all projects of the authenticated user*
- [POST] /api/v1/project - Creates a new project*
- [PUT] /api/v1/project/:id - Updated an existing project*
- [PUT] /api/v1/project/:id/name - Update the project name*
- [DELETE] /api/v1/project/:id - Delete an existing project*
- [GET] /api/v1/project/:id - Retrieves the project by id

*Only for authenticated Users

## OAuth authentication and authorization flow

For the authentication there will be an external service in order to manage the user easily.

Here some ideas:
- Auth0
- Firebase
- Supabase

> **Note** Auth0 will be used for authentication

Users will be able to authenticate through Github provider. Once authenticated, they will send a token to the server that will take care of validating it. If not present, the user will be synchronized in the database without saving any personal information. You only need to enter an identifier. Also, users wil be able to **delete** their profile whenever they want, but they will not be able to restore their snippets.

> **Warning** Checklist is still in WIP

# Task list
> **Note** Part of task are done by #300

### @codeimage/app
- [X] https://github.com/riccardoperra/codeimage/issues/240
   > **Note** users must be able to delete their account (ask for feedback)
- [x] https://github.com/riccardoperra/codeimage/issues/241
- [x] <del>https://github.com/riccardoperra/codeimage/issues/55</del> To rework
- [X] Add dashboard page
- [x] Add ability to clone snippets https://github.com/riccardoperra/codeimage/pull/336
- [X] Add possibility to rename the snippet "workspace"
- [X] Refactor store state
- [X] Synchronize state with backend
- [X] Add base confirm dialog component
- [X] Move secondary actions to header menu (language selection, profile page, theme mode)
- [X] Add in-memory local storage to use CodeImage without backend in dev mode https://github.com/riccardoperra/codeimage/pull/338
- [X] Handle toasts for actions https://github.com/riccardoperra/codeimage/pull/347
- [x] View-mode snippet page / Standalone read-only editor page when accessing snippet by link without edit permissions (only owners can edit their snippets) https://github.com/riccardoperra/codeimage/pull/336
- [x] Handle api errors and exceptions #329 https://github.com/riccardoperra/codeimage/pull/337
- [x] Handle better page transition and loading with suspense https://github.com/riccardoperra/codeimage/pull/350
- [x] Improve projects list performance with virtual-scroll https://github.com/riccardoperra/codeimage/pull/342 https://github.com/riccardoperra/codeimage/pull/345
- [x] Refactor ui store with new atomic-state approach?
- [x] Update hero-icons to 2.0

- [x] Responsive/Adaptive layout
- [x] Add basic api `makeFetch` interface
- [x] ~~Add profile page section with ability to delete the profile~~ Delayed to 1.1

### @codeimage/api
- [ ] Add backend documentation
- [x] ~~Add possibility to delete current user and related snippets~~ Delayed to 1.1
- [x] Configure CORS to use api with different origins through preview/next deploy https://github.com/riccardoperra/codeimage/pull/354
- [x] Clone snippets https://github.com/riccardoperra/codeimage/pull/336
- [ ] Add benchmarking and performance improvements

### @codeimage/ui
- [X] Add RadioField component with @solid-aria
- [X] Add IconButton component https://github.com/riccardoperra/codeimage/pull/335
- [x] Refactor button component to handle both pointer and default cursor
- [x] Add badge component
- [X] Add menu component with solid-aria
- [X] Refactor `Text` component to have variants with base text or description (used also for FieldLabel) https://github.com/riccardoperra/codeimage/pull/353
- [X] Refactor `Text` component to get configuration from his context https://github.com/riccardoperra/codeimage/pull/353
- [x] Remove style attributes using @codeimage/ui components
- [X] Refactor toast component with `solid-toast` https://github.com/riccardoperra/codeimage/pull/347

### Core
- [ ] Improve packages build speed
- [ ] Improve and fix typings
- [ ] Update README for contributions
- [ ] Update packages documentation
- [ ] Improve release/preview CI/CD workflow with Github Action
- [ ] Improve feature stability
